artifacts_root : artifacts

data_ingestion :
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/arch-adi21/NLP-Learning/raw/main/summarizer-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion